import type { Metadata } from "next";
import localFont from "next/font/local";
import {
    ClerkProvider,
    SignedIn,
    SignedOut,
    RedirectToSignIn,
} from "@clerk/nextjs";
import "./globals.css";
import Navbar from "@/app/(components)/navbar/page";
import {ChatWidget} from "@/app/(components)/chat/ChatWidget";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Subizwa",
  description: "Generated by create next app and powered by Fabish",
};

export default function RootLayout({children,}: {
  children: React.ReactNode;
}) {
  return (
      <ClerkProvider>
        <html lang="en">
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <Navbar />
        {children}
        <SignedOut>
          <body />
        </SignedOut>
        <SignedIn>
            <ChatWidget />
        </SignedIn>
        </body>
        </html>
      </ClerkProvider>
  );
}
